-- config.lua
-- Defines default user configurations

local config = {
	numeric_mode = false,
	debug = false,
	log_level = "INFO",
	cache_enabled = true,
	cache_max_entries = 100,
	cache_ttl = 3600,
	enable_default_mappings = true,
	domains = { "arithmetic", "calculus", "linear_algebra", "differential_equations" },
	process_timeout_ms = 30000,
	result_separator = " = ",
	result_display = "insert",
	max_jobs = 5,
	persistent_variable_assignment_operator = ":=",
	backend = "wolfram",
	backend_opts = {
		wolfram = {
			wolfram_path = "wolframscript",
			function_mappings = {
				sin = "Sin",
				cos = "Cos",
				tan = "Tan",
				arcsin = "ArcSin",
				arccos = "ArcCos",
				arctan = "ArcTan",
				sinh = "Sinh",
				cosh = "Cosh",
				tanh = "Tanh",
				arsinh = "ArcSinh",
				arcosh = "ArcCosh",
				artanh = "ArcTanh",
				log = "Log",
				ln = "Log",
				log10 = "Log10",
				exp = "Exp",
				u = "HeavisideTheta",
			},
		},
	},
	plotting = {
		backend = "wolfram",
		usetex = true,
		latex_engine = "pdflatex",
		latex_preamble = "",
		outputmode = "latex",
		filename_mode = "hash",
    viewer_cmd_pdf = vim.fn.has("macunix") == 1 and "open" or "xdg-open",
    viewer_cmd_png = vim.fn.has("macunix") == 1 and "open" or "xdg-open",
		default_xrange = { -10, 10 },
		default_yrange = { -10, 10 },
		default_zrange = { -10, 10 },
		default_t_range = { -10, 10 },
		default_theta_range = { 0, "2*pi" },
		default_urange = { -10, 10 },
		default_vrange = { -10, 10 },
	},
	hooks = {},
}

return config
